### ISSUE TITLE
Solution File

### ISSUE THREAD

**Issue by allendukes** [mitchellcairns/robochefs#2]
The .gitignore removed the solution file from the repo. Could we get it back? Or some instructions on how to generate one? I have unity installed and I cloned the repo, but I don't know where to go from there. Looking for some help!

**Comment by barraudf** [comment]
sln file is generated on-the-fly by Unity.

All you have to do is clone this repo to a local folder on your computer, open an existing project with unity, pointing to that folder, and you're done.

**Comment by mitchellcairns** [comment]
barraudf has the right idea, you just open the project in Unity.
