### ISSUE TITLE
Corrupted .obj & .fbx files

### ISSUE THREAD

**Issue by LillianSo** [mitchellcairns/robochefs#4]
Hi,

I'm aware that this is now over a year old, but I hope someone can still help me. I downloaded the project as a .zip, but for the life of me, I can't get it to work. The models somehow come out all corrupted. Can anyone help me? Perhaps upload it as a working Unitypackage somewhere?
Thanks in advance! Can't wait to work with this!

**Comment by VALLIS-NERIA** [comment]
try using git clone instead of downloading .zip file

**Comment by ilhamprayogi123** [comment]
i have the same problem with this project,

using git didn't work for me, is anyone have solution about this,

thanks

**Comment by isp123** [comment]
i have the same problem with this project,

using git didn't work for me, is anyone have solution about this,

thanks

**Comment by VALLIS-NERIA** [comment]
@LillianSo @isp123 the author uses git-lfs to store models. Make sure you have git-lfs installed and can be found in PATH. Or install GitHub Desktop client.

**Comment by mitchellcairns** [comment]
Hi everyone,

Sorry for ignoring this. I don't actively come on here anymore so here's a link: https://drive.google.com/file/d/1fMVLcw_AGFlCwufvDJzswquPMJBErv5I/view?usp=sharing

**Comment by LillianSo** [comment]
@mitchellcairns You're amazing. Thank you!

**Comment by mitchellcairns** [comment]
Files may not load due to depreciation of Google Poly asset loader. Sorry y'all!
